name: Docker Compose

on: 
  pull_request:
    branches: 
      - master
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the docker-compose
      run: docker-compose build
